name: OrgWarden
author: Tech AI
description: |
  Audit an organization for best practices with OrgWarden.
  See https://github.com/gt-tech-ai/OrgWarden for more information.
branding:
  icon: lock
  color: blue

inputs:
  org-url:
    description: |
      Full URL of the GitHub organization you would like to audit.
      Example: https://github.com/gt-tech-ai
    required: true
  github-pat:
    description: |
      A GitHub Personal Access Token (PAT).
      See https://github.com/gt-tech-ai/OrgWarden#setting-up-a-personal-access-token for help.
    required: true
  repository-audit-settings:
    description: |
      Allows you to alter audit behavior on an individual repository basis by providing a sequence of settings strings.
      See https://github.com/gt-tech-ai/OrgWarden#repository-specific-settings for help.
      Example format: "OrgWarden: --GitHub-AutoMerge-false" "my-repo: --GitHub-License-value MIT"
    required: false
  modules:
    description: |
      The RepoAuditor modules you would like to run. If not provided, OrgWarden will run all RepoAuditor modules.
      Modules should be deliminated by a single space.
      Example: "GitHub My-Module GitHub-Customization"
      See https://github.com/gt-sse-center/RepoAuditor for available modules.
    required: False
  include-all-private-repos:
    description: |
      Include all of your organization's private repositories in OrgWarden's audit.
      Default: false.
    required: false
  included-private-repos:
    description: |
      Specific private repositories to include in OrgWarden's audit.
      Repositories should be deliminated by a single space.
      Example: "MyPrivateRepo top-secret-tool unfinished-project"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout OrgWarden Locally
      uses: actions/checkout@v4
      with:
        repository: gt-tech-ai/OrgWarden
        ref: v0

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Install Dependencies
      run: uv sync --frozen --quiet
      shell: bash

    - name: Run OrgWarden
      env:
        # Must be converted to an enviroment variable in order to preserve single and double quotes
        REPO_AUDIT_SETTINGS: ${{ inputs.repository-audit-settings }}
      run: |
        # OrgWarden
        CYAN="\033[0;36m"
        echo -e "${CYAN}Now Running OrgWarden"
        
        command="uv run orgwarden audit ${{ inputs.org-url }} ${{ inputs.github-pat }} $REPO_AUDIT_SETTINGS"

        if echo "${{ inputs.include-all-private-repos }}" | grep -i "true"; then
          command+=" --include-all-private-repos"
        elif [ -n "${{ inputs.included-private-repos }}" ]; then
          private_repos=(${{ inputs.included-private-repos }})
          for repo in "${private_repos[@]}"; do
            command+=" --include-private-repo $repo"
          done
        fi

        if [ -n "${{ inputs.modules }}" ]; then
          modules=(${{ inputs.modules }})
          for module in "${modules[@]}"; do
            command+=" --module $module"
          done
        fi

        echo Running Command: $command
        eval $command
      shell: bash
      