[project]
name = "orgwarden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "austin-weeks", email = "austinweeksmusic@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
orgwarden = "orgwarden:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
