name: CI

on: 
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run Tests
        run: uv run pytest